### ISSUE TITLE
Your gitignore isn't a .gitignore and thus isn't being used

### ISSUE THREAD

**Issue by adamtuliper** [siukk/Class-10-Git-Homework#1]
replace your gitignore with a .gitignore as per the homework. Note your library folder is being included and it shouldn't be.
you should then delete your library folder and then do a git add -A .  and then commit and push again. When you open Unity then AFTER this it will rebuild your library folder.

**Comment by siukk** [comment]
Thanks for the heads up professor, the naming convention must have failed when I downloaded from Google Drive as I did it fairly hastily. Sorry about that, thanks again!
